[tool.poetry]
authors     = ["Eric Busto <ebusto@nvidia.com>"]
description = "Publish changes to a message broker"
name        = "nautobot-change-producer"
packages    = [{include = "nautobot_change_producer"}]
readme      = "README.md"
version     = "2.1.2"

[tool.poetry.dependencies]
dictdiffer = "^0.9.0"
nats-py    = "^2.9.0"
nkeys      = "^0.2.1"
orjson     = "^3.10.12"
python     = "^3.10"

[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires      = ["poetry-core"]


[tool.ruff]
line-length = 120
target-version = "py38"

[tool.ruff.lint]
select = [
    "D",  # pydocstyle
    "F", "E", "W",  # flake8
    "S",  # bandit
    "I",  # isort
]
ignore = [
    # warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible.
    "D203", # 1 blank line required before class docstring

    # D212 is enabled by default in google convention, and complains if we have a docstring like:
    # """
    # My docstring is on the line after the opening quotes instead of on the same line as them.
    # """
    # We've discussed and concluded that we consider this to be a valid style choice.
    "D212", # Multi-line docstring summary should start at the first line
    "D213", # Multi-line docstring summary should start at the second line

    # Produces a lot of issues in the current codebase.
    "D401", # First line of docstring should be in imperative mood
    "D407", # Missing dashed underline after section
    "D416", # Section name ends in colon
    "E501", # Line too long
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"nautobot_change_producer/tests/*" = [
    "D",
    "S"
]

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing", "thread"]
include = [
    "nautobot_change_producer/*"
]
omit = [
    "nautobot_change_producer/tests/*",
]