---
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VER: "${NAUTOBOT_VER}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    dockerfile: "develop/Dockerfile"
  image: "networktocode/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
  volumes:
    - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
    - "../:/source"
  env_file:
    - ".env"
  tty: true

services:
  nautobot:
    ports:
      - "8080:8080"
    depends_on:
      - "redis"
      - "db"
    <<: *nautobot-build
  worker:
    entrypoint: "nautobot-server celery worker -B -l INFO"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-build

  db:
    image: "postgres:13-alpine"
    env_file:
      - ".env"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: "10s"
      timeout: "5s"
      retries: 10

  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - ".env"
    ports:
      - "6379:6379"

  nats:
    image: "docker.io/nats:2.9.20"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "nats:/data"
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

volumes:
  postgres_data: {}
  nats: {}
